apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: frontend-application
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    destination:
        name: in-cluster
        namespace: argocd
    source:
        path: kubernetes/applications/frontend
        repoURL: 'https://github.com/Guanart/SIP-2024-grupo-1.git'
        targetRevision: HEAD
    project: frontend-project
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
