services:
  postgres-db:
    image: postgres:15.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: '03' # Configura zona horaria del contenedor (Argentina)
    volumes:
      - postgres_data_sip:/var/lib/postgresql/data
      
    ports:
      - ${DATABASE_PORT}:5432

volumes:
  postgres_data_sip: