apiVersion: v1
kind: Service
metadata:
    name: backend-service
    namespace: argocd
spec:
    type: LoadBalancer
    selector:
        app: backend
    ports:
        - name: https
          protocol: TCP
          port: 3443
          targetPort: 3443
        - name: http
          protocol: TCP
          port: 3000
          targetPort: 3000
