apiVersion: v1
kind: Service
metadata:
    name: backend-service
    namespace: argocd
spec:
    type: ClusterIP
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
