# https://www.digitalocean.com/community/tutorials/how-to-deploy-postgres-to-kubernetes-cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-volume-claim
    namespace: postgres-namespace
    labels:
        app: postgres
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 10Gi
