apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: argocd
spec:
    type: LoadBalancer
    selector:
        app: frontend
    ports:
        - name: https
          protocol: TCP
          port: 443
          targetPort: 443
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
