apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: argocd
spec:
    type: LoadBalancer
    loadBalancerIP: <RESERVED_IP>
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 5173 # 80 / 443
          targetPort: 80
