apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: argocd
spec:
    replicas: 3
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: 'grupo4sdypp2024/lot-frontend:latest'
                  imagePullPolicy: Always
                  ports:
                      #   - containerPort: 80
                      - containerPort: 443 # Agregado para prueba de https

            # Agrega toleration para asegurar que los pods se creen unicamente en el node group de aplicaciones
            tolerations:
                - key: instance_type
                  operator: Equal
                  value: applications
                  effect: NoSchedule
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: role
                                    operator: In
                                    values:
                                        - applications
