apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: argocd
spec:
    type: LoadBalancer
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 443
          targetPort: 443
