apiVersion: v1
kind: Namespace
metadata:
    name: backend-namespace
---
apiVersion: v1
kind: Namespace
metadata:
    name: frontend-namespace
---
apiVersion: v1
kind: Namespace
metadata:
    name: postgres-namespace
