apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
    namespace: cert-manager
spec:
    acme:
        email: johndoe@gmail.com
        server: https://acme-v02.api.letsencrypt.org/directory # Servidor de producción
        privateKeySecretRef:
            name: cluster-issuer-account-key
        solvers:
            - dns01:
                  cloudflare:
                      email: johndoe@gmail.com
                      apiTokenSecretRef:
                          name: cloudflare-token-secret
                          key: cloudflare-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-staging
    namespace: cert-manager
spec:
    acme:
        email: johndoe@gmail.com
        server: https://acme-staging-v02.api.letsencrypt.org/directory # Servidor de pruebas
        privateKeySecretRef:
            name: cluster-issuer-account-key
        solvers:
            - dns01:
                  cloudflare:
                      email: johndoe@gmail.com
                      apiTokenSecretRef:
                          name: cloudflare-token-secret
                          key: cloudflare-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: certificate
    namespace: cert-manager
spec:
    secretName: certificate-tls
    issuerRef:
        name: letsencrypt-prod # letsencrypt-staging
        kind: ClusterIssuer
    commonName: 'leagueoftoken.online'
    dnsNames:
        - 'leagueoftoken.online'
        - 'frontend.leagueoftoken.online'
        - 'api.leagueoftoken.online'
