# https://www.digitalocean.com/community/tutorials/how-to-deploy-postgres-to-kubernetes-cluster
apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-volume
    namespace: postgres-namespace
    labels:
        type: local
        app: postgres
spec:
    storageClassName: manual
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: /var/data/postgresql
        type: DirectoryOrCreate
