apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: postgres-cluster
    namespace: argocd
spec:
    instances: 3
    imageName: ghcr.io/cloudnative-pg/postgresql:15.3
    storage:
        size: 1Gi
    bootstrap:
        initdb:
            database: LOT # Inicializa la BDD vacía
            owner: app
    enableSuperuserAccess: true
    backup:
        barmanObjectStore:
            destinationPath: 'gs://lot-pg-backups'
            googleCredentials:
                gkeEnvironment: true
    serviceAccountTemplate:
        metadata:
            annotations:
                iam.gke.io/gcp-service-account: cnpg-backup@sip-2024-grupo-1.iam.gserviceaccount.com
    monitoring:
        enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
    name: postgres-cluster-scheduled-backup
    namespace: argocd
spec:
    schedule: '*/30 * * * *' # Cada media hora y '0 2 * * *' Se ejecuta 2 AM todos los días
    backupOwnerReference: self
    cluster:
        name: postgres-cluster
    immediate: true
    method: barmanObjectStore
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
    name: postgres-cluster-backup
    namespace: argocd
spec:
    cluster:
        name: postgres-cluster
    method: barmanObjectStore
